version: '3.1'

services:
  app:
    build: .
    ports:
      - 8001:8001
    networks:
      - go-shop-app
    command: gin -a 8000 -p 8001 run main.go
    volumes:
      - .:/app
    depends_on: 
      - db
    env_file:
      - ./env/app.env
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./env/db.env
    networks:
      - go-shop-app
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./env/mongo-express.env
    networks:
      - go-shop-app
networks:
  go-shop-app: